namespace: azure_factory
name: monitoring
version: 1.0.0
readme: README.md
authors:
  - Azure Factory Team
description: Azure Factory collection for monitoring resources (Log Analytics, Application Insights, etc.)
license_file: LICENSE
tags:
  - azure
  - monitoring
  - loganalytics
  - applicationinsights
dependencies: {}
repository: https://github.com/your-org/azure-factory
documentation: https://github.com/your-org/azure-factory
homepage: https://github.com/your-org/azure-factory
issues: https://github.com/your-org/azure-factory/issues