namespace: azure_factory
name: network
version: 1.0.0
readme: README.md
authors:
  - Azure Factory Team
description: Azure Factory collection for network resources (VNet, NSG, subnets)
license_file: LICENSE
tags:
  - azure
  - network
  - vnet
  - nsg
dependencies: {}
repository: https://github.com/your-org/azure-factory
documentation: https://github.com/your-org/azure-factory
homepage: https://github.com/your-org/azure-factory
issues: https://github.com/your-org/azure-factory/issues