---
# Private DNS Zone Role - Main Tasks
# This role creates a private DNS zone for Web App private endpoints using ONLY Azure CLI commands

- name: Validate required variables
  fail:
    msg: "{{ item }} is required but not defined"
  when: lookup('vars', item) is not defined or lookup('vars', item) == ""
  loop:
    - dns_zone_name
    - resource_group_name
    - vnet_name

- name: Check if Private DNS Zone already exists using Azure CLI
  command: az network private-dns zone show --resource-group "{{ resource_group_name }}" --name "{{ dns_zone_name }}"
  register: dns_zone_check
  failed_when: false
  changed_when: false

- name: Create Private DNS Zone using Azure CLI
  command: az network private-dns zone create --resource-group "{{ resource_group_name }}" --name "{{ dns_zone_name }}" --tags "{{ dns_zone_tags | default('Project={{ project_name }} Environment={{ env_name }} ManagedBy=Ansible') }}"
  register: dns_zone_result
  when: dns_zone_check.rc != 0
  changed_when: dns_zone_result.rc == 0

- name: Get VNet information using Azure CLI
  command: az network vnet show --resource-group "{{ resource_group_name }}" --name "{{ vnet_name }}"
  register: vnet_info
  changed_when: false

- name: Check if DNS Zone is linked to VNet using Azure CLI
  command: az network private-dns link vnet list --resource-group "{{ resource_group_name }}" --zone-name "{{ dns_zone_name }}" --query "[?virtualNetwork.id=='{{ (vnet_info.stdout | from_json).id if vnet_info.stdout != '' else '' }}']" -o tsv
  register: dns_link_check
  failed_when: false
  changed_when: false
  when: vnet_info.stdout != ''

- name: Check if DNS Zone is linked to VNet using Azure CLI (fallback)
  command: az network private-dns link vnet list --resource-group "{{ resource_group_name }}" --zone-name "{{ dns_zone_name }}" -o tsv
  register: dns_link_check_fallback
  failed_when: false
  changed_when: false
  when: vnet_info.stdout == ''

- name: Set DNS link check result
  set_fact:
    dns_link_check: "{{ dns_link_check_fallback if vnet_info.stdout == '' else dns_link_check }}"

- name: Link Private DNS Zone to VNet using Azure CLI
  command: az network private-dns link vnet create --resource-group "{{ resource_group_name }}" --zone-name "{{ dns_zone_name }}" --name "{{ dns_zone_name }}-link" --virtual-network "{{ vnet_name }}" --registration-enabled false
  register: dns_link_result
  when: dns_link_check.stdout == ""
  changed_when: dns_link_result.rc == 0

- name: Display Private DNS Zone information
  debug:
    msg:
      - "Private DNS Zone: {{ dns_zone_name }}"
      - "Resource Group: {{ resource_group_name }}"
      - "VNet: {{ vnet_name }}"
      - "Status: {{ 'Created' if dns_zone_check.rc != 0 else 'Already exists' }}"
      - "Linked: {{ 'Yes' if dns_link_check.stdout != '' or dns_link_result is defined else 'No' }}"
  when: display_dns_info | default(true)

- name: Set Private DNS Zone facts
  set_fact:
    dns_zone_resource_group: "{{ resource_group_name }}"
    dns_zone_name: "{{ dns_zone_name }}"
    dns_zone_exists: "{{ dns_zone_check.rc == 0 }}"