---
# PostgreSQL Database Deployment Group Variables - Development Environment
# These variables are specific to the development environment for PostgreSQL deployment using Azure CLI commands only

# Environment-specific settings
env_name: dev
project_name: "myapp"
default_location: "Southeast Asia"

# Resource naming conventions
resource_prefix: "{{ project_name }}-{{ env_name }}"

# Azure Authentication (use environment variables or Ansible Vault)
azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') | default('') }}"
azure_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') | default('') }}"
azure_auth_method: "{{ lookup('env', 'AZURE_AUTH_METHOD') | default('cli') }}"

# Resource Group Configuration
resource_group_name: "{{ project_name }}-{{ env_name }}-rg"
resource_group_location: "{{ default_location }}"
location: "{{ resource_group_location }}"  # Alias for PostgreSQL role

# Network Configuration
vnet_name: "{{ project_name }}-{{ env_name }}-vnet"
vnet_address_prefix: "10.0.0.0/16"

# Subnet Configuration
delegated_subnet_name: "appservice-delegated"
non_delegated_subnet_name: "appservice-private"
delegated_subnet_prefix: "10.0.1.0/24"
non_delegated_subnet_prefix: "10.0.2.0/24"

# PostgreSQL Flexible Server Configuration
postgresql_server_name: "{{ project_name }}-{{ env_name }}-postgres"
postgresql_admin_username: "postgresadmin"
postgresql_admin_password: "{{ vault_postgresql_password }}"  # Use Ansible Vault
postgresql_version: "15"  # Supported versions: 13, 14, 15, 16
postgresql_sku_name: "B_Standard_B1ms"  # Minimal pricing tier for development
postgresql_tier: "Burstable"  # Burstable, GeneralPurpose, MemoryOptimized
postgresql_storage_size: 32  # Minimum storage size in GB
postgresql_backup_retention: 7  # Backup retention in days
postgresql_geo_redundant_backup: false  # Disable for cost optimization
postgresql_high_availability: false  # Disable for cost optimization
postgresql_zone: "1"  # Availability zone
postgresql_public_access: false  # Private access only
postgresql_ssl_enforcement: true  # Enable SSL enforcement
postgresql_minimal_tls_version: "TLS1_2"  # Minimum TLS version

# PostgreSQL Database Configuration
postgresql_databases:
  - name: "{{ project_name }}_{{ env_name }}_db"
    charset: "UTF8"
    collation: "en_US.UTF8"
  - name: "{{ project_name }}_{{ env_name }}_test_db"
    charset: "UTF8"
    collation: "en_US.UTF8"

# PostgreSQL Firewall Rules Configuration
postgresql_firewall_rules:
  - name: "AllowAzureServices"
    start_ip: "0.0.0.0"
    end_ip: "0.0.0.0"
    description: "Allow Azure services to access the server"

# Private Endpoint Configuration
enable_private_endpoint: true
private_endpoint_name: "{{ project_name }}-{{ env_name }}-postgres-pe"
private_endpoint_subnet: "database"  # Use existing database subnet
private_endpoint_group_ids: ["postgresqlServer"]  # PostgreSQL group ID

# Private DNS Zone Configuration
enable_private_dns_zone: true
private_dns_zone_name: "privatelink.postgres.database.azure.com"
private_dns_record_name: "{{ postgresql_server_name }}"

# UAMI Integration Configuration
enable_uami_integration: true
uami_name: "{{ project_name }}-{{ env_name }}-uami"  # Use existing UAMI from webapp
uami_resource_id: ""  # Will be populated from existing UAMI

# PostgreSQL Performance Configuration
postgresql_performance_tuning:
  shared_preload_libraries: "pg_stat_statements"
  max_connections: 100
  shared_buffers: "256MB"
  effective_cache_size: "1GB"
  maintenance_work_mem: "64MB"
  checkpoint_completion_target: 0.9
  wal_buffers: "16MB"
  default_statistics_target: 100

# PostgreSQL Monitoring Configuration
enable_monitoring: true
log_retention_days: 30

# PostgreSQL Cost Optimization Settings
cost_optimization:
  auto_pause_delay: 60  # Auto-pause after 60 minutes of inactivity
  auto_pause_enabled: true  # Enable auto-pause for dev environments
  storage_autogrow: false  # Disable storage autogrow
  backup_redundancy: "Local"  # Use local redundancy

# NSG Configuration
nsg_name: "{{ project_name }}-{{ env_name }}-nsg"
nsg_rules:
  - name: "AllowPostgreSQL"
    priority: 1000
    direction: "Inbound"
    access: "Allow"
    protocol: "Tcp"
    source_port_range: "*"
    destination_port_range: "5432"
    source_address_prefix: "10.0.0.0/16"  # Allow from VNet only
    destination_address_prefix: "*"

# Security settings
enable_ddos_protection: false
enable_vm_protection: false
enable_service_endpoints: true
enable_nsg_flow_logs: false

# Validation settings
validate_env_vars: true
validate_auth: true
validate_postgresql_config: true
validate_network_config: true
validate_uami_config: true

# Display settings
display_postgresql_info: true
display_private_endpoint_info: true
display_dns_info: true
display_uami_info: true

# Output settings
save_postgresql_info: false
postgresql_info_file: "./postgresql-deployment-summary-{{ project_name }}-{{ env_name }}.txt"

# Development-specific tags
postgresql_tags:
  Project: "{{ project_name }}"
  Environment: "{{ env_name }}"
  ManagedBy: "Ansible"
  ResourceType: "PostgreSQLFlexibleServer"
  CostCenter: "Development"
  Owner: "DevTeam"
  BackupRequired: "false"
  MonitoringEnabled: "true"
  PrivateAccess: "true"
  UAMIEnabled: "true"
  DatabaseType: "PostgreSQL"
  Version: "{{ postgresql_version }}"
  Tier: "{{ postgresql_tier }}"
