---
# PostgreSQL Private Endpoint Role Default Variables
# These variables define default values for PostgreSQL private endpoint configuration using Azure CLI commands only

# Private Endpoint Configuration
private_endpoint_name: "{{ project_name }}-{{ env_name }}-postgres-pe"
private_endpoint_subnet: "database"  # Use existing database subnet
private_endpoint_group_ids: ["postgresqlServer"]  # PostgreSQL group ID

# Private DNS Zone Configuration
enable_private_dns_zone: true
private_dns_zone_name: "privatelink.postgres.database.azure.com"
private_dns_record_name: "{{ postgresql_server_name }}"

# Network Configuration
vnet_name: "{{ project_name }}-{{ env_name }}-vnet"
resource_group_name: "{{ project_name }}-{{ env_name }}-rg"

# Validation Settings
validate_network_config: true

# Display Settings
display_private_endpoint_info: true

# Tags
postgresql_tags:
  Project: "{{ project_name }}"
  Environment: "{{ env_name }}"
  ManagedBy: "Ansible"
  ResourceType: "PostgreSQLPrivateEndpoint"
  CostCenter: "{{ 'Development' if env_name == 'dev' else 'Production' }}"
