---
# Production Environment Inventory
all:
  children:
    azure_prod:
      hosts:
        localhost:
      vars:
        environment: prod
        project_name: "myapp"
        azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        azure_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
        azure_auth_method: "{{ lookup('env', 'AZURE_AUTH_METHOD') | default('cli') }}"
        default_location: "East US"
        
        # Network configuration
        vnet_name: "{{ project_name }}-{{ environment }}-vnet"
        vnet_address_prefix: "10.1.0.0/16"
        subnets:
          - name: "frontend"
            address_prefix: "10.1.1.0/24"
            service_endpoints: []
          - name: "backend"
            address_prefix: "10.1.2.0/24"
            service_endpoints: []
          - name: "database"
            address_prefix: "10.1.3.0/24"
            service_endpoints: ["Microsoft.Sql", "Microsoft.Storage"]
          - name: "management"
            address_prefix: "10.1.4.0/24"
            service_endpoints: []
        
        # NSG configuration - more restrictive for production
        nsg_rules:
          - name: "AllowSSHFromBastion"
            priority: 1000
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "22"
            source_address_prefix: "10.1.4.0/24"
            destination_address_prefix: "*"
          - name: "AllowHTTP"
            priority: 1100
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "80"
            source_address_prefix: "*"
            destination_address_prefix: "*"
          - name: "AllowHTTPS"
            priority: 1200
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "443"
            source_address_prefix: "*"
            destination_address_prefix: "*"
          - name: "DenyAllInbound"
            priority: 4000
            direction: "Inbound"
            access: "Deny"
            protocol: "*"
            source_port_range: "*"
            destination_port_range: "*"
            source_address_prefix: "*"
            destination_address_prefix: "*"
