---
# Development Environment Inventory
all:
  children:
    azure_dev:
      hosts:
        localhost:
      vars:
        env_name: dev
        project_name: "myapp"
        azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        azure_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
        azure_auth_method: "{{ lookup('env', 'AZURE_AUTH_METHOD') | default('cli') }}"
        default_location: "Southeast Asia"
        
        # Resource Group Configuration
        resource_group_name: "{{ project_name }}-{{ env_name }}-rg"
        resource_group_location: "{{ default_location }}"
        location: "{{ resource_group_location }}"  # Alias for App Service Plan role
        
        # App Service Plan Configuration
        app_service_plan_name: "{{ project_name }}-{{ env_name }}-asp"
        sku_name: "B1"  # Basic tier - supports private endpoints
        sku_tier: "Basic"
        sku_size: "B1"
        sku_capacity: 1
        app_service_plan_kind: "Linux"  # Linux or Windows
        app_service_plan_reserved: true  # Required for Linux plans
        
        # Web App Configuration
        webapp_name: "{{ project_name }}-{{ env_name }}-webapp"
        webapp_framework: "python"  # python, node, dotnet, java, php
        webapp_framework_version: "3.9"  # Version of the framework
        
        # Subnet Configuration
        delegated_subnet_name: "appservice-delegated"
        non_delegated_subnet_name: "appservice-private"
        delegated_subnet_prefix: "10.0.1.0/24"
        non_delegated_subnet_prefix: "10.0.2.0/24"
        
        # Network configuration
        vnet_name: "{{ project_name }}-{{ env_name }}-vnet"
        vnet_address_prefix: "10.0.0.0/16"
        nsg_name: "{{ project_name }}-{{ env_name }}-nsg"
        
        # Private Endpoint configuration
        private_endpoint_name: "{{ project_name }}-{{ env_name }}-pe"
        enable_private_endpoint: true  # Enabled for Basic tier
        dns_zone_name: "privatelink.azurewebsites.net"
        private_endpoint_group_ids: ["sites"]
        
        # User Assigned Managed Identity configuration
        enable_user_assigned_identity: true
        user_assigned_identity_name: "{{ project_name }}-{{ env_name }}-uami"
        
        # Custom Domain configuration
        custom_domain_name: ""  # Empty to use default Azure domain
        create_dns_zone: false
        create_ssl_certificate: false
        subnets:
          - name: "frontend"
            address_prefix: "10.0.1.0/24"
            service_endpoints: []
          - name: "backend"
            address_prefix: "10.0.2.0/24"
            service_endpoints: []
          - name: "database"
            address_prefix: "10.0.3.0/24"
            service_endpoints: ["Microsoft.Sql", "Microsoft.Storage"]
        
        # NSG configuration
        nsg_rules:
          - name: "AllowSSH"
            priority: 1000
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "22"
            source_address_prefix: "*"
            destination_address_prefix: "*"
          - name: "AllowHTTP"
            priority: 1100
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "80"
            source_address_prefix: "*"
            destination_address_prefix: "*"
          - name: "AllowHTTPS"
            priority: 1200
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "443"
            source_address_prefix: "*"
            destination_address_prefix: "*"
