namespace: azure_factory
name: database
version: 1.0.0
readme: README.md
authors:
  - Azure Factory Team
description: Azure Factory collection for database resources (SQL Server, PostgreSQL, etc.)
license_file: LICENSE
tags:
  - azure
  - database
  - sql
  - postgresql
dependencies: {}
repository: https://github.com/your-org/azure-factory
documentation: https://github.com/your-org/azure-factory
homepage: https://github.com/your-org/azure-factory
issues: https://github.com/your-org/azure-factory/issues