---
# Complete VNet Role Defaults
# Default values for the complete VNet role

vnet_name: "{{ project_name }}-{{ env_name }}-vnet"
vnet_address_prefix: "10.0.0.0/16"
vnet_dns_servers: []
vnet_tags:
  Project: "{{ project_name }}"
  Environment: "{{ env_name }}"
  ManagedBy: "Ansible"
  Type: "VirtualNetwork"

nsg_name: "{{ project_name }}-{{ env_name }}-nsg"
nsg_tags:
  Project: "{{ project_name }}"
  Environment: "{{ env_name }}"
  ManagedBy: "Ansible"
  Type: "NetworkSecurityGroup"

# Default NSG rules
nsg_rules:
  - name: "AllowSSH"
    priority: 1000
    direction: "Inbound"
    access: "Allow"
    protocol: "Tcp"
    source_port_range: "*"
    destination_port_range: "22"
    source_address_prefix: "*"
    destination_address_prefix: "*"
  - name: "AllowHTTP"
    priority: 1100
    direction: "Inbound"
    access: "Allow"
    protocol: "Tcp"
    source_port_range: "*"
    destination_port_range: "80"
    source_address_prefix: "*"
    destination_address_prefix: "*"
  - name: "AllowHTTPS"
    priority: 1200
    direction: "Inbound"
    access: "Allow"
    protocol: "Tcp"
    source_port_range: "*"
    destination_port_range: "443"
    source_address_prefix: "*"
    destination_address_prefix: "*"
  - name: "AllowRDP"
    priority: 1300
    direction: "Inbound"
    access: "Allow"
    protocol: "Tcp"
    source_port_range: "*"
    destination_port_range: "3389"
    source_address_prefix: "*"
    destination_address_prefix: "*"

# Default subnets
subnets:
  - name: "frontend"
    address_prefix: "10.0.1.0/24"
    service_endpoints: []
  - name: "backend"
    address_prefix: "10.0.2.0/24"
    service_endpoints: []
  - name: "database"
    address_prefix: "10.0.3.0/24"
    service_endpoints: ["Microsoft.Sql", "Microsoft.Storage"]

display_vnet_info: true
