---
# Azure Authentication Role Variables
# These variables can be overridden in playbooks or inventory

# Authentication validation
validate_auth: true

# Resource group creation
create_resource_group: true

# Location validation
validate_location: true

# Tag validation
validate_tags: true
